# This is a basic workflow to help you get started with Actions

name: CI

# Controls when press the W key you go forward If you use the A key you go left If you use the S key you go backwards if you use the D you go right
# events but only for the MinecraftWithDetail branch
on:
  push:
    branches: [ MinecraftWithDetail ]
  pull_request:
    branches: [ MinecraftWithDetail ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
